# config.yaml
tokenizers:
  - bpe_naive
  - bpe_fast
  - wp_naive
  - wp_fast

vocab_sizes:
  - 20000

n_train:
  - 500

morpho_benchmark_id: "axmeu/FrVMorpho"
wikipedia_hub_id:    "axmeu/BPE_WP_dataset"