[workspace]
name = "bpe-wp-project"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]


[dependencies]
python = ">=3.11"
tqdm = "*"
ipykernel = "*"


[pypi-dependencies]
datasets = "*"
huggingface-hub = "*"